name: Build Chrome Extension

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build  # Assuming your build script is called "build" in package.json

      - name: Zip extension files
        run: |
          zip -r extension.zip ./dist/*  # Adjust this path if needed

      - name: Upload extension zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: extension.zip

      # - name: Publish extension to Chrome Web Store (optional)
      #   run: |
      #     # Add a step to publish to the Chrome Web Store, if desired.
      #     # For example, using chrome-webstore-upload-cli
